# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e56fc0da95097853077c2d75cfef5c245f07c8f8a1f38d68660436c4a824d66c72ba1b3fcd20ac209634c2a01df9259195fc5446a743e5a52d5ce231c8b65633

test:
  secret_key_base: d2da79368ebc4c34d89d871caa6381c9269dffdcb8d3e5d290127851bac9886c2ce3007408555276cfefd2421f10117418cd18fe0dc1e7267cad28ec8cd37461

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
